"""Common UK grocery search terms so catalogs stay comparable across chains."""

from __future__ import annotations

SEED_QUERIES: list[str] = [
    "milk",
    "semi skimmed milk",
    "bread",
    "white bread",
    "eggs",
    "butter",
    "cheddar",
    "yoghurt",
    "bananas",
    "apples",
    "potatoes",
    "tomatoes",
    "chicken breast",
    "mince",
    "bacon",
    "salmon",
    "pasta",
    "rice",
    "baked beans",
    "cereal",
    "porridge",
    "coffee",
    "tea bags",
    "orange juice",
    "cola",
    "water",
    "crisps",
    "chocolate",
    "biscuits",
    "ice cream",
    "frozen pizza",
    "toilet roll",
    "washing up liquid",
    "laundry detergent",
    "shampoo",
    "toothpaste",
    "olive oil",
    "sugar",
    "flour",
    "onions",
]
