"""Common UK grocery search terms so catalogs stay comparable across chains."""

from __future__ import annotations

SEED_QUERIES: list[str] = [
    # Staples
    "milk",
    "semi skimmed milk",
    "whole milk",
    "bread",
    "white bread",
    "brown bread",
    "eggs",
    "free range eggs",
    "butter",
    "spreadable butter",
    "cheddar",
    "mature cheddar",
    "yoghurt",
    "greek yoghurt",
    # Produce
    "bananas",
    "apples",
    "potatoes",
    "tomatoes",
    "onions",
    "carrots",
    "broccoli",
    "cucumber",
    "lettuce",
    "avocados",
    "lemons",
    "grapes",
    # Meat / fish
    "chicken breast",
    "chicken thighs",
    "mince",
    "beef mince",
    "bacon",
    "sausages",
    "salmon",
    "cod fillets",
    "ham",
    # Pantry
    "pasta",
    "spaghetti",
    "rice",
    "basmati rice",
    "baked beans",
    "tinned tomatoes",
    "cereal",
    "porridge",
    "oats",
    "coffee",
    "instant coffee",
    "tea bags",
    "orange juice",
    "apple juice",
    "cola",
    "sparkling water",
    "water",
    "olive oil",
    "sunflower oil",
    "sugar",
    "flour",
    "salt",
    "pepper",
    "ketchup",
    "mayonnaise",
    "peanut butter",
    "jam",
    "honey",
    # Snacks / frozen
    "crisps",
    "chocolate",
    "biscuits",
    "digestives",
    "ice cream",
    "frozen pizza",
    "frozen chips",
    "fish fingers",
    # Household / personal care
    "toilet roll",
    "kitchen roll",
    "washing up liquid",
    "laundry detergent",
    "fabric softener",
    "shampoo",
    "toothpaste",
    "deodorant",
    "bin bags",
    "nappies",
]
