"""Common German grocery search terms so catalogs stay comparable across chains."""

from __future__ import annotations

SEED_QUERIES: list[str] = [
    # Staples / dairy
    "Milch",
    "Vollmilch",
    "H-Milch",
    "Butter",
    "Margarine",
    "Eier",
    "Freilandeier",
    "Käse",
    "Gouda",
    "Joghurt",
    "Quark",
    "Sahne",
    # Bread / bakery
    "Brot",
    "Vollkornbrot",
    "Toastbrot",
    "Brötchen",
    # Produce
    "Apfel",
    "Banane",
    "Tomaten",
    "Kartoffeln",
    "Zwiebeln",
    "Karotten",
    "Gurke",
    "Salat",
    "Paprika",
    "Zitronen",
    "Trauben",
    "Avocado",
    # Meat / cold cuts
    "Hähnchen",
    "Hähnchenbrust",
    "Hackfleisch",
    "Wurst",
    "Leberwurst",
    "Schinken",
    "Bacon",
    "Lachs",
    # Pantry
    "Nudeln",
    "Spaghetti",
    "Reis",
    "Basmatireis",
    "Mehl",
    "Zucker",
    "Salz",
    "Pfeffer",
    "Öl",
    "Olivenöl",
    "Essig",
    "Ketchup",
    "Mayonnaise",
    "Senf",
    "Marmelade",
    "Honig",
    "Erdnussbutter",
    "Dosentomaten",
    "Baked Beans",
    # Breakfast / drinks
    "Müsli",
    "Haferflocken",
    "Kaffee",
    "Filterkaffee",
    "Tee",
    "Orangensaft",
    "Apfelsaft",
    "Cola",
    "Wasser",
    "Mineralwasser",
    "Bier",
    # Snacks / frozen / sweets
    "Schokolade",
    "Kekse",
    "Chips",
    "Eis",
    "Tiefkühlpizza",
    "Pommes",
    "Fischstäbchen",
    # Household / personal care
    "Toilettenpapier",
    "Küchenrolle",
    "Spülmittel",
    "Waschmittel",
    "Weichspüler",
    "Shampoo",
    "Zahnpasta",
    "Deo",
    "Müllbeutel",
    "Windeln",
]
